[package]
    authors     = ["Rhelvetican"]
    description = "A simple Balatro CLI mod manager. Focuses on `lovely` and `smods` mods."
    edition     = "2024"
    keywords    = ["balatro", "manager", "mod"]
    license     = "MIT"
    name        = "dagger-balatro"
    version     = "0.1.0-prealpha3"

[[bin]]
    name = "dg"
    path = "src/bin/dg.rs"

[dependencies]
    clap          = { features = ["derive"], version = "4" }
    git2          = { features = ["https"], version = "0.20" }
    mimalloc-rust = "0.2"
    serde         = { features = ["derive"], version = "1" }
    serde_json    = "1"
    thiserror     = "2"
    toml          = "0.9"
    url           = "2"
